### ISSUE TITLE
Instalacja

### ISSUE THREAD

**Issue by Jordan87** [PePeLLee/home-assistant-rce#1]
Cześć

"Integrację należy pobrać do folderu custom_components/rce **i dodać poprzez ustawienia HA** (nie przez edycje konfiguracji yaml)"

Po wrzuceniu plikow trzeba zrobic restart i powinien byc w dodatkach HA czy cos innego miales na mysli przez "ustawienia HA"?

**Comment by PePeLLee** [comment]
Po dodaniu integracji od katalogu trzeba zrestartować HA a potem dodaje się przez:
![image](https://github.com/PePeLLee/home-assistant-rce/assets/61408245/2fd4b0e5-10ac-48d8-9072-c141a9c8f838)

**Comment by Jordan87** [comment]
A to od razu tzreba bylo napisac ze przez opcje "dodaj integracje" :)

**Comment by Jordan87** [comment]
W pierwszej wersji integracja nie wystawia jeszcze encji z cena z danej godziny ktora mozna by uzyc jako zrodlo dla zakladki "Energia"?
![image](https://github.com/PePeLLee/home-assistant-rce/assets/10414918/898fe69a-6c7e-4d8c-8dc1-f94c00f645c9)

**Comment by PePeLLee** [comment]
Zarówno z mojego lenistwa jak i dla Twojego bezpieczeństwa polecam sobie zrobić własną encję typy template sensor i wyciągać wartość z kalendarza. W przypadku jakiejś zmiany w integracji, lub kiedy ktoś zrobi coś lepszego, wystarczy ze zmienisz template i nie będziesz tracił historii.

**Comment by Jordan87** [comment]
Ok, to bede musial pokombinowac jak to zrobic. Dzieki

**Comment by PePeLLee** [comment]
Np. coś takiego, tylko nie wiem czy energy dashboard nie potrzebuje dodatkowych ustawień typu device class.
```
template:
  - sensor:
      - name: "Aktualna cena"
        unit_of_measurement: "zł/kWh"
        state: >
           {{state_attr("calendar.rce_calendar","message")| replace(",",".")| float}}
```

**Comment by Jordan87** [comment]
Dzieki, działa

Musiałem na ten moment lekko zmodyfikowac bo RCE podaje wartosc za MWh a oczywiscie potrzebuje kWh wiec podzielilem przez -1000
```
    - name: "Aktualna cena"
      unit_of_measurement: "zł/kWh"
      state: >
        {{ (state_attr("calendar.rce_calendar","message")| replace(",",".")| float)/1000 }}
```
Bede tylko musial dokladnie przyobserwowac czy czasem dla zakladki energia nie bedzie trzeba brac z godziny poprzedniej z nie bierzącej bo nie wiem jak to zadziala przy zliczaniu na przelomie kazdej godziny, chyba ze twoja iontegracja wprowadza i tak pewne opoznienie wiec nei ma strachu przed pobraniem ceny z kolejnej godziny :)

**Comment by PePeLLee** [comment]
Jak możesz zobaczyć w widoku kalendarza przez cały dzień masz dostępne wszystkie wartości dla wszystkich godzin więc jeżeli byłaby taka potrzeba to możesz pobrać wartość z następnego a nie aktualnego wydarzenia kalendarza.

**Comment by Jordan87** [comment]
Tak tylko dla potomnych napisze ze na bazie jednego dnia wyglada ze w takiej formie zaciaga prawidlowa cene dla energii wyslanej w danej godzinie ;)

**Comment by Jordan87** [comment]
Doszedłem do wniosku że dla bezpieczeństwa było by lepiej aktualizowac cene np 1min po kazdej okrągłej godzinie, nie wiedzialem jak to zrobic z template twoim wiec z podpowiedza chatgpt zrobilem sensor i automatyzacje ktora bedzie go aktualizowac minute po kazdej okraglej godzinie.

Dodatkowo gdyby cena RCE pojawila sie ujemna, cena sprzedazy energii powinna byc traktowana jako 0 a nie wartosc ujemna wiec zmodyfikowalem go w ten sposob:

```
  - platform: template
    sensors:
      aktualna_cena_sensor:
        friendly_name: "Aktualna cena sensor"
        unit_of_measurement: "zł/kWh"
        value_template: >
          {{ max((state_attr("calendar.rce_calendar", "message")| replace(",", ".")| float)/1000, 0) }}
```
